---
- hosts: default
  gather_facts: false
  remote_user: root
  become: true

  tasks:
    - name: Remove existing certbot package
      apt:
        name: certbot
        state: absent

    - name: Install certbot
      snap:
        name: certbot
        classic: yes
    
    - name: Prepare certbot command
      file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        owner: root
        group: root
        state: link

    - command: which certbot
      register: which_certbot

    - debug: var=which_certbot.stdout_lines

